# Generated by Django 4.2 on 2026-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
