# Generated by Django 4.2 on 2026-04-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept_id',
            new_name='dept',
        ),
    ]
